// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	core "Bank-repository-service/pkg/core"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICardRepository is a mock of ICardRepository interface.
type MockICardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICardRepositoryMockRecorder
}

// MockICardRepositoryMockRecorder is the mock recorder for MockICardRepository.
type MockICardRepositoryMockRecorder struct {
	mock *MockICardRepository
}

// NewMockICardRepository creates a new mock instance.
func NewMockICardRepository(ctrl *gomock.Controller) *MockICardRepository {
	mock := &MockICardRepository{ctrl: ctrl}
	mock.recorder = &MockICardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICardRepository) EXPECT() *MockICardRepositoryMockRecorder {
	return m.recorder
}

// Blocking mocks base method.
func (m *MockICardRepository) Blocking(ctx context.Context, id int64) (*core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocking", ctx, id)
	ret0, _ := ret[0].(*core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocking indicates an expected call of Blocking.
func (mr *MockICardRepositoryMockRecorder) Blocking(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocking", reflect.TypeOf((*MockICardRepository)(nil).Blocking), ctx, id)
}

// Create mocks base method.
func (m *MockICardRepository) Create(ctx context.Context, input *core.Card) (*core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICardRepositoryMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICardRepository)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockICardRepository) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockICardRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICardRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockICardRepository) GetAll(ctx context.Context) ([]core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICardRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICardRepository)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockICardRepository) GetById(ctx context.Context, id int64) (*core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICardRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICardRepository)(nil).GetById), ctx, id)
}

// GetByNumber mocks base method.
func (m *MockICardRepository) GetByNumber(ctx context.Context, number string) (*core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNumber", ctx, number)
	ret0, _ := ret[0].(*core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNumber indicates an expected call of GetByNumber.
func (mr *MockICardRepositoryMockRecorder) GetByNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNumber", reflect.TypeOf((*MockICardRepository)(nil).GetByNumber), ctx, number)
}

// GetByUser mocks base method.
func (m *MockICardRepository) GetByUser(ctx context.Context, idUser int64) ([]core.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, idUser)
	ret0, _ := ret[0].([]core.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockICardRepositoryMockRecorder) GetByUser(ctx, idUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockICardRepository)(nil).GetByUser), ctx, idUser)
}
