// Code generated by MockGen. DO NOT EDIT.
// Source: interface_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	common "github.com/Suinar/Bank-proto/repository/common"
	deposit "github.com/Suinar/Bank-proto/repository/deposit"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIDepositService is a mock of IDepositService interface.
type MockIDepositService struct {
	ctrl     *gomock.Controller
	recorder *MockIDepositServiceMockRecorder
}

// MockIDepositServiceMockRecorder is the mock recorder for MockIDepositService.
type MockIDepositServiceMockRecorder struct {
	mock *MockIDepositService
}

// NewMockIDepositService creates a new mock instance.
func NewMockIDepositService(ctrl *gomock.Controller) *MockIDepositService {
	mock := &MockIDepositService{ctrl: ctrl}
	mock.recorder = &MockIDepositServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDepositService) EXPECT() *MockIDepositServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIDepositService) Create(ctx context.Context, req *deposit.Deposit) (*deposit.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*deposit.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIDepositServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIDepositService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockIDepositService) Delete(ctx context.Context, req *common.IdRequest) (*common.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIDepositServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIDepositService)(nil).Delete), ctx, req)
}

// GetAll mocks base method.
func (m *MockIDepositService) GetAll(ctx context.Context, req *common.Empty) (*deposit.DepositList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, req)
	ret0, _ := ret[0].(*deposit.DepositList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIDepositServiceMockRecorder) GetAll(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIDepositService)(nil).GetAll), ctx, req)
}

// GetById mocks base method.
func (m *MockIDepositService) GetById(ctx context.Context, req *common.IdRequest) (*deposit.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, req)
	ret0, _ := ret[0].(*deposit.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIDepositServiceMockRecorder) GetById(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIDepositService)(nil).GetById), ctx, req)
}

// GetByUser mocks base method.
func (m *MockIDepositService) GetByUser(ctx context.Context, req *common.UserIdRequest) (*deposit.DepositList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, req)
	ret0, _ := ret[0].(*deposit.DepositList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockIDepositServiceMockRecorder) GetByUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockIDepositService)(nil).GetByUser), ctx, req)
}

// Replenish mocks base method.
func (m *MockIDepositService) Replenish(ctx context.Context, req *common.AmountRequest) (*deposit.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replenish", ctx, req)
	ret0, _ := ret[0].(*deposit.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replenish indicates an expected call of Replenish.
func (mr *MockIDepositServiceMockRecorder) Replenish(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replenish", reflect.TypeOf((*MockIDepositService)(nil).Replenish), ctx, req)
}


