// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_cache.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/kVinsom/Bank-repository-service/pkg/core"
)

// MockICurrencyCache is a mock of ICurrencyCache interface.
type MockICurrencyCache struct {
	ctrl     *gomock.Controller
	recorder *MockICurrencyCacheMockRecorder
}

// MockICurrencyCacheMockRecorder is the mock recorder for MockICurrencyCache.
type MockICurrencyCacheMockRecorder struct {
	mock *MockICurrencyCache
}

// NewMockICurrencyCache creates a new mock instance.
func NewMockICurrencyCache(ctrl *gomock.Controller) *MockICurrencyCache {
	mock := &MockICurrencyCache{ctrl: ctrl}
	mock.recorder = &MockICurrencyCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICurrencyCache) EXPECT() *MockICurrencyCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockICurrencyCache) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICurrencyCacheMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICurrencyCache)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockICurrencyCache) GetAll(ctx context.Context) ([]core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICurrencyCacheMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICurrencyCache)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockICurrencyCache) GetById(ctx context.Context, id int64) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICurrencyCacheMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICurrencyCache)(nil).GetById), ctx, id)
}

// GetByIso mocks base method.
func (m *MockICurrencyCache) GetByIso(ctx context.Context, iso string) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIso", ctx, iso)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIso indicates an expected call of GetByIso.
func (mr *MockICurrencyCacheMockRecorder) GetByIso(ctx, iso interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIso", reflect.TypeOf((*MockICurrencyCache)(nil).GetByIso), ctx, iso)
}

// GetBySymbol mocks base method.
func (m *MockICurrencyCache) GetBySymbol(ctx context.Context, symbol rune) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbol", ctx, symbol)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbol indicates an expected call of GetBySymbol.
func (mr *MockICurrencyCacheMockRecorder) GetBySymbol(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbol", reflect.TypeOf((*MockICurrencyCache)(nil).GetBySymbol), ctx, symbol)
}

// Set mocks base method.
func (m *MockICurrencyCache) Set(ctx context.Context, currency *core.Currency) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, currency)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockICurrencyCacheMockRecorder) Set(ctx, currency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockICurrencyCache)(nil).Set), ctx, currency)
}

// SetAll mocks base method.
func (m *MockICurrencyCache) SetAll(ctx context.Context, currencies []core.Currency) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAll", ctx, currencies)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAll indicates an expected call of SetAll.
func (mr *MockICurrencyCacheMockRecorder) SetAll(ctx, currencies interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAll", reflect.TypeOf((*MockICurrencyCache)(nil).SetAll), ctx, currencies)
}

// Update mocks base method.
func (m *MockICurrencyCache) Update(ctx context.Context, currency *core.Currency) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, currency)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICurrencyCacheMockRecorder) Update(ctx, currency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICurrencyCache)(nil).Update), ctx, currency)
}
