// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	core "github.com/Suinar/Bank-repository-service/pkg/core"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICreditRepository is a mock of ICreditRepository interface.
type MockICreditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICreditRepositoryMockRecorder
}

// MockICreditRepositoryMockRecorder is the mock recorder for MockICreditRepository.
type MockICreditRepositoryMockRecorder struct {
	mock *MockICreditRepository
}

// NewMockICreditRepository creates a new mock instance.
func NewMockICreditRepository(ctrl *gomock.Controller) *MockICreditRepository {
	mock := &MockICreditRepository{ctrl: ctrl}
	mock.recorder = &MockICreditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreditRepository) EXPECT() *MockICreditRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICreditRepository) Create(ctx context.Context, input *core.Credit) (*core.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*core.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICreditRepositoryMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICreditRepository)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockICreditRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICreditRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICreditRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockICreditRepository) GetAll(ctx context.Context) ([]core.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]core.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICreditRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICreditRepository)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockICreditRepository) GetById(ctx context.Context, id int64) (*core.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*core.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICreditRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICreditRepository)(nil).GetById), ctx, id)
}

// GetByUser mocks base method.
func (m *MockICreditRepository) GetByUser(ctx context.Context, idUser int64) ([]core.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, idUser)
	ret0, _ := ret[0].([]core.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockICreditRepositoryMockRecorder) GetByUser(ctx, idUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockICreditRepository)(nil).GetByUser), ctx, idUser)
}

// Repay mocks base method.
func (m *MockICreditRepository) Repay(ctx context.Context, id, amount int64) (*core.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repay", ctx, id, amount)
	ret0, _ := ret[0].(*core.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repay indicates an expected call of Repay.
func (mr *MockICreditRepositoryMockRecorder) Repay(ctx, id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repay", reflect.TypeOf((*MockICreditRepository)(nil).Repay), ctx, id, amount)
}



