// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	core "Bank-repository-service/pkg/core"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICurrencyRepository is a mock of ICurrencyRepository interface.
type MockICurrencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICurrencyRepositoryMockRecorder
}

// MockICurrencyRepositoryMockRecorder is the mock recorder for MockICurrencyRepository.
type MockICurrencyRepositoryMockRecorder struct {
	mock *MockICurrencyRepository
}

// NewMockICurrencyRepository creates a new mock instance.
func NewMockICurrencyRepository(ctrl *gomock.Controller) *MockICurrencyRepository {
	mock := &MockICurrencyRepository{ctrl: ctrl}
	mock.recorder = &MockICurrencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICurrencyRepository) EXPECT() *MockICurrencyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICurrencyRepository) Create(ctx context.Context, input *core.Currency) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICurrencyRepositoryMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICurrencyRepository)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockICurrencyRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICurrencyRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICurrencyRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockICurrencyRepository) GetAll(ctx context.Context) ([]core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICurrencyRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICurrencyRepository)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockICurrencyRepository) GetById(ctx context.Context, id int64) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICurrencyRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICurrencyRepository)(nil).GetById), ctx, id)
}

// GetByIso mocks base method.
func (m *MockICurrencyRepository) GetByIso(ctx context.Context, isoCode string) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIso", ctx, isoCode)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIso indicates an expected call of GetByIso.
func (mr *MockICurrencyRepositoryMockRecorder) GetByIso(ctx, isoCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIso", reflect.TypeOf((*MockICurrencyRepository)(nil).GetByIso), ctx, isoCode)
}

// GetBySymbol mocks base method.
func (m *MockICurrencyRepository) GetBySymbol(ctx context.Context, symbol rune) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbol", ctx, symbol)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbol indicates an expected call of GetBySymbol.
func (mr *MockICurrencyRepositoryMockRecorder) GetBySymbol(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbol", reflect.TypeOf((*MockICurrencyRepository)(nil).GetBySymbol), ctx, symbol)
}

// Update mocks base method.
func (m *MockICurrencyRepository) Update(ctx context.Context, id int64, input *core.CurrencyUpdateInput) (*core.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*core.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockICurrencyRepositoryMockRecorder) Update(ctx, id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICurrencyRepository)(nil).Update), ctx, id, input)
}
