// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	core "Bank-repository-service/pkg/core"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIDepositRepository is a mock of IDepositRepository interface.
type MockIDepositRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIDepositRepositoryMockRecorder
}

// MockIDepositRepositoryMockRecorder is the mock recorder for MockIDepositRepository.
type MockIDepositRepositoryMockRecorder struct {
	mock *MockIDepositRepository
}

// NewMockIDepositRepository creates a new mock instance.
func NewMockIDepositRepository(ctrl *gomock.Controller) *MockIDepositRepository {
	mock := &MockIDepositRepository{ctrl: ctrl}
	mock.recorder = &MockIDepositRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDepositRepository) EXPECT() *MockIDepositRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIDepositRepository) Create(ctx context.Context, input *core.Deposit) (*core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIDepositRepositoryMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIDepositRepository)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockIDepositRepository) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIDepositRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIDepositRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockIDepositRepository) GetAll(ctx context.Context) ([]core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIDepositRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIDepositRepository)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockIDepositRepository) GetById(ctx context.Context, id int64) (*core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIDepositRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIDepositRepository)(nil).GetById), ctx, id)
}

// GetByUser mocks base method.
func (m *MockIDepositRepository) GetByUser(ctx context.Context, idUser int64) ([]core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, idUser)
	ret0, _ := ret[0].([]core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockIDepositRepositoryMockRecorder) GetByUser(ctx, idUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockIDepositRepository)(nil).GetByUser), ctx, idUser)
}

// Replenish mocks base method.
func (m *MockIDepositRepository) Replenish(ctx context.Context, id int64, amount int) (*core.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replenish", ctx, id, amount)
	ret0, _ := ret[0].(*core.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replenish indicates an expected call of Replenish.
func (mr *MockIDepositRepositoryMockRecorder) Replenish(ctx, id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replenish", reflect.TypeOf((*MockIDepositRepository)(nil).Replenish), ctx, id, amount)
}
