services:
  postgres:
    image: postgres:16
    container_name: bank_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/migration/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgres/migration/create-test-db.sql:/docker-entrypoint-initdb.d/02-create-test-db.sql
      - ./postgres/migration/init_test.sql:/docker-entrypoint-initdb.d/03-init-test.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: bank_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


volumes:
  postgres_data: