// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: repository/account/account.proto

package account

import (
	context "context"

	common "Bank-repository-service/proto/repository/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountRepository_GetAll_FullMethodName    = "/repository.account.AccountRepository/GetAll"
	AccountRepository_GetByUser_FullMethodName = "/repository.account.AccountRepository/GetByUser"
	AccountRepository_GetById_FullMethodName   = "/repository.account.AccountRepository/GetById"
	AccountRepository_Create_FullMethodName    = "/repository.account.AccountRepository/Create"
	AccountRepository_Blocking_FullMethodName  = "/repository.account.AccountRepository/Blocking"
	AccountRepository_Close_FullMethodName     = "/repository.account.AccountRepository/Close"
	AccountRepository_Update_FullMethodName    = "/repository.account.AccountRepository/Update"
	AccountRepository_Delete_FullMethodName    = "/repository.account.AccountRepository/Delete"
)

// AccountRepositoryClient is the client API for AccountRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountRepositoryClient interface {
	GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AccountList, error)
	GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*AccountList, error)
	GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Account, error)
	Create(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	Blocking(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Account, error)
	Close(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Account, error)
	Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*Account, error)
	Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error)
}

type accountRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountRepositoryClient(cc grpc.ClientConnInterface) AccountRepositoryClient {
	return &accountRepositoryClient{cc}
}

func (c *accountRepositoryClient) GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AccountList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountList)
	err := c.cc.Invoke(ctx, AccountRepository_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRepositoryClient) GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*AccountList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountList)
	err := c.cc.Invoke(ctx, AccountRepository_GetByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRepositoryClient) GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountRepository_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRepositoryClient) Create(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountRepository_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRepositoryClient) Blocking(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountRepository_Blocking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRepositoryClient) Close(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountRepository_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRepositoryClient) Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, AccountRepository_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRepositoryClient) Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.DeleteResponse)
	err := c.cc.Invoke(ctx, AccountRepository_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountRepositoryServer is the server API for AccountRepository service.
// All implementations must embed UnimplementedAccountRepositoryServer
// for forward compatibility.
type AccountRepositoryServer interface {
	GetAll(context.Context, *common.Empty) (*AccountList, error)
	GetByUser(context.Context, *common.UserIdRequest) (*AccountList, error)
	GetById(context.Context, *common.IdRequest) (*Account, error)
	Create(context.Context, *Account) (*Account, error)
	Blocking(context.Context, *common.IdRequest) (*Account, error)
	Close(context.Context, *common.IdRequest) (*Account, error)
	Update(context.Context, *UpdateAccountRequest) (*Account, error)
	Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error)
	mustEmbedUnimplementedAccountRepositoryServer()
}

// UnimplementedAccountRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountRepositoryServer struct{}

func (UnimplementedAccountRepositoryServer) GetAll(context.Context, *common.Empty) (*AccountList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedAccountRepositoryServer) GetByUser(context.Context, *common.UserIdRequest) (*AccountList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByUser not implemented")
}
func (UnimplementedAccountRepositoryServer) GetById(context.Context, *common.IdRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedAccountRepositoryServer) Create(context.Context, *Account) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAccountRepositoryServer) Blocking(context.Context, *common.IdRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method Blocking not implemented")
}
func (UnimplementedAccountRepositoryServer) Close(context.Context, *common.IdRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedAccountRepositoryServer) Update(context.Context, *UpdateAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAccountRepositoryServer) Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAccountRepositoryServer) mustEmbedUnimplementedAccountRepositoryServer() {}
func (UnimplementedAccountRepositoryServer) testEmbeddedByValue()                           {}

// UnsafeAccountRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountRepositoryServer will
// result in compilation errors.
type UnsafeAccountRepositoryServer interface {
	mustEmbedUnimplementedAccountRepositoryServer()
}

func RegisterAccountRepositoryServer(s grpc.ServiceRegistrar, srv AccountRepositoryServer) {
	// If the following call panics, it indicates UnimplementedAccountRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountRepository_ServiceDesc, srv)
}

func _AccountRepository_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).GetAll(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRepository_GetByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).GetByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_GetByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).GetByUser(ctx, req.(*common.UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRepository_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).GetById(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).Create(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRepository_Blocking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).Blocking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_Blocking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).Blocking(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRepository_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).Close(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRepository_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).Update(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountRepository_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRepositoryServer).Delete(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountRepository_ServiceDesc is the grpc.ServiceDesc for AccountRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.account.AccountRepository",
	HandlerType: (*AccountRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _AccountRepository_GetAll_Handler,
		},
		{
			MethodName: "GetByUser",
			Handler:    _AccountRepository_GetByUser_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _AccountRepository_GetById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountRepository_Create_Handler,
		},
		{
			MethodName: "Blocking",
			Handler:    _AccountRepository_Blocking_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _AccountRepository_Close_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountRepository_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/account/account.proto",
}
