syntax = "proto3";

package repository.account;

option go_package = "github.com/Suinar/Bank-repository-service/proto/repository/account";

import "repository/common/common.proto";

enum AccountStatus {
  ACCOUNT_STATUS_CLOSED = 0;
  ACCOUNT_STATUS_ACTIVE = 1;
  ACCOUNT_STATUS_BLOCKED = 2;
}

message Account {
  int64 id = 1;
  int64 user_id = 2;
  int64 currency_id = 3;

  string name = 4;
  int64 balance = 5;

  AccountStatus status = 6;
}

message AccountUpdateInput {
  optional string name = 1;
}

message AccountList {
  repeated Account accounts = 1;
}

message UpdateAccountRequest {
  int64 id = 1;
  AccountUpdateInput input = 2;
}

service AccountRepository {
  rpc GetAll(repository.common.Empty)
      returns (AccountList);

  rpc GetByUser(repository.common.UserIdRequest)
      returns (AccountList);

  rpc GetById(repository.common.IdRequest)
      returns (Account);

  rpc Create(Account)
      returns (Account);

  rpc Blocking(repository.common.IdRequest)
      returns (Account);

  rpc Close(repository.common.IdRequest)
      returns (Account);

  rpc Update(UpdateAccountRequest)
      returns (Account);

  rpc Delete(repository.common.IdRequest)
      returns (repository.common.Empty);
}