// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: repository/account/account.proto

package __

import (
	common "github.com/Suinar/Bank-repository-service/proto/repository/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_CLOSED  AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ACTIVE  AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_BLOCKED AccountStatus = 2
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_CLOSED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_BLOCKED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_CLOSED":  0,
		"ACCOUNT_STATUS_ACTIVE":  1,
		"ACCOUNT_STATUS_BLOCKED": 2,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_account_account_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_repository_account_account_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_repository_account_account_proto_rawDescGZIP(), []int{0}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Status        AccountStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=repository.account.AccountStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_repository_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_repository_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_repository_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Account) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_CLOSED
}

type AccountCreateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,2,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCreateInput) Reset() {
	*x = AccountCreateInput{}
	mi := &file_repository_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreateInput) ProtoMessage() {}

func (x *AccountCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_repository_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreateInput.ProtoReflect.Descriptor instead.
func (*AccountCreateInput) Descriptor() ([]byte, []int) {
	return file_repository_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCreateInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AccountCreateInput) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *AccountCreateInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AccountUpdateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountUpdateInput) Reset() {
	*x = AccountUpdateInput{}
	mi := &file_repository_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUpdateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUpdateInput) ProtoMessage() {}

func (x *AccountUpdateInput) ProtoReflect() protoreflect.Message {
	mi := &file_repository_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUpdateInput.ProtoReflect.Descriptor instead.
func (*AccountUpdateInput) Descriptor() ([]byte, []int) {
	return file_repository_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountUpdateInput) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type AccountList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountList) Reset() {
	*x = AccountList{}
	mi := &file_repository_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountList) ProtoMessage() {}

func (x *AccountList) ProtoReflect() protoreflect.Message {
	mi := &file_repository_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountList.ProtoReflect.Descriptor instead.
func (*AccountList) Descriptor() ([]byte, []int) {
	return file_repository_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *AccountList) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         *AccountUpdateInput    `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_repository_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_repository_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAccountRequest) GetInput() *AccountUpdateInput {
	if x != nil {
		return x.Input
	}
	return nil
}

var File_repository_account_account_proto protoreflect.FileDescriptor

const file_repository_account_account_proto_rawDesc = "" +
	"\n" +
	" repository/account/account.proto\x12\x12repository.account\x1a\x17repository/common.proto\"\xbc\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcurrency_id\x18\x03 \x01(\x03R\n" +
	"currencyId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.repository.account.AccountStatusR\x06status\"b\n" +
	"\x12AccountCreateInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcurrency_id\x18\x02 \x01(\x03R\n" +
	"currencyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"6\n" +
	"\x12AccountUpdateInput\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"F\n" +
	"\vAccountList\x127\n" +
	"\baccounts\x18\x01 \x03(\v2\x1b.repository.account.AccountR\baccounts\"d\n" +
	"\x14UpdateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12<\n" +
	"\x05input\x18\x02 \x01(\v2&.repository.account.AccountUpdateInputR\x05input*a\n" +
	"\rAccountStatus\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_BLOCKED\x10\x022\xe4\x04\n" +
	"\x11AccountRepository\x12C\n" +
	"\x06GetAll\x12\x18.repository.common.Empty\x1a\x1f.repository.account.AccountList\x12N\n" +
	"\tGetByUser\x12 .repository.common.UserIdRequest\x1a\x1f.repository.account.AccountList\x12D\n" +
	"\aGetById\x12\x1c.repository.common.IdRequest\x1a\x1b.repository.account.Account\x12M\n" +
	"\x06Create\x12&.repository.account.AccountCreateInput\x1a\x1b.repository.account.Account\x12E\n" +
	"\bBlocking\x12\x1c.repository.common.IdRequest\x1a\x1b.repository.account.Account\x12B\n" +
	"\x05Close\x12\x1c.repository.common.IdRequest\x1a\x1b.repository.account.Account\x12O\n" +
	"\x06Update\x12(.repository.account.UpdateAccountRequest\x1a\x1b.repository.account.Account\x12I\n" +
	"\x06Delete\x12\x1c.repository.common.IdRequest\x1a!.repository.common.DeleteResponseB\x03Z\x01/b\x06proto3"

var (
	file_repository_account_account_proto_rawDescOnce sync.Once
	file_repository_account_account_proto_rawDescData []byte
)

func file_repository_account_account_proto_rawDescGZIP() []byte {
	file_repository_account_account_proto_rawDescOnce.Do(func() {
		file_repository_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_account_account_proto_rawDesc), len(file_repository_account_account_proto_rawDesc)))
	})
	return file_repository_account_account_proto_rawDescData
}

var file_repository_account_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repository_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_repository_account_account_proto_goTypes = []any{
	(AccountStatus)(0),            // 0: repository.account.AccountStatus
	(*Account)(nil),               // 1: repository.account.Account
	(*AccountCreateInput)(nil),    // 2: repository.account.AccountCreateInput
	(*AccountUpdateInput)(nil),    // 3: repository.account.AccountUpdateInput
	(*AccountList)(nil),           // 4: repository.account.AccountList
	(*UpdateAccountRequest)(nil),  // 5: repository.account.UpdateAccountRequest
	(*common.Empty)(nil),          // 6: repository.common.Empty
	(*common.UserIdRequest)(nil),  // 7: repository.common.UserIdRequest
	(*common.IdRequest)(nil),      // 8: repository.common.IdRequest
	(*common.DeleteResponse)(nil), // 9: repository.common.DeleteResponse
}
var file_repository_account_account_proto_depIdxs = []int32{
	0,  // 0: repository.account.Account.status:type_name -> repository.account.AccountStatus
	1,  // 1: repository.account.AccountList.accounts:type_name -> repository.account.Account
	3,  // 2: repository.account.UpdateAccountRequest.input:type_name -> repository.account.AccountUpdateInput
	6,  // 3: repository.account.AccountRepository.GetAll:input_type -> repository.common.Empty
	7,  // 4: repository.account.AccountRepository.GetByUser:input_type -> repository.common.UserIdRequest
	8,  // 5: repository.account.AccountRepository.GetById:input_type -> repository.common.IdRequest
	2,  // 6: repository.account.AccountRepository.Create:input_type -> repository.account.AccountCreateInput
	8,  // 7: repository.account.AccountRepository.Blocking:input_type -> repository.common.IdRequest
	8,  // 8: repository.account.AccountRepository.Close:input_type -> repository.common.IdRequest
	5,  // 9: repository.account.AccountRepository.Update:input_type -> repository.account.UpdateAccountRequest
	8,  // 10: repository.account.AccountRepository.Delete:input_type -> repository.common.IdRequest
	4,  // 11: repository.account.AccountRepository.GetAll:output_type -> repository.account.AccountList
	4,  // 12: repository.account.AccountRepository.GetByUser:output_type -> repository.account.AccountList
	1,  // 13: repository.account.AccountRepository.GetById:output_type -> repository.account.Account
	1,  // 14: repository.account.AccountRepository.Create:output_type -> repository.account.Account
	1,  // 15: repository.account.AccountRepository.Blocking:output_type -> repository.account.Account
	1,  // 16: repository.account.AccountRepository.Close:output_type -> repository.account.Account
	1,  // 17: repository.account.AccountRepository.Update:output_type -> repository.account.Account
	9,  // 18: repository.account.AccountRepository.Delete:output_type -> repository.common.DeleteResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_repository_account_account_proto_init() }
func file_repository_account_account_proto_init() {
	if File_repository_account_account_proto != nil {
		return
	}
	file_repository_account_account_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_account_account_proto_rawDesc), len(file_repository_account_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_account_account_proto_goTypes,
		DependencyIndexes: file_repository_account_account_proto_depIdxs,
		EnumInfos:         file_repository_account_account_proto_enumTypes,
		MessageInfos:      file_repository_account_account_proto_msgTypes,
	}.Build()
	File_repository_account_account_proto = out.File
	file_repository_account_account_proto_goTypes = nil
	file_repository_account_account_proto_depIdxs = nil
}
