syntax = "proto3";

package repository;

option go_package = "/";

enum AccountStatus {
  ACCOUNT_STATUS_CLOSED = 0;
  ACCOUNT_STATUS_ACTIVE = 1;
  ACCOUNT_STATUS_BLOCKED = 2;
}

message Account {
  int64 id = 1;
  int64 user_id = 2;
  int64 currency_id = 3;

  string name = 4;
  int64 balance = 5;

  AccountStatus status = 6;
}

message AccountCreateInput {
  int64 user_id = 1;
  int64 currency_id = 2;
  string name = 3;
}

message AccountUpdateInput {
  optional string name = 1;
}

message AccountList {
  repeated Account accounts = 1;
}

message IdRequest {
  int64 id = 1;
}

message UserIdRequest {
  int64 user_id = 1;
}

message Empty {}

message DeleteResponse {
  int64 rows_affected = 1;
}

message UpdateAccountRequest {
  int64 id = 1;
  AccountUpdateInput input = 2;
}

service AccountRepository {
  rpc GetAll(Empty) returns (AccountList);
  rpc GetByUser(UserIdRequest) returns (AccountList);
  rpc GetById(IdRequest) returns (Account);

  rpc Create(AccountCreateInput) returns (Account);
  rpc Blocking(IdRequest) returns (Account);
  rpc Close(IdRequest) returns (Account);

  rpc Update(UpdateAccountRequest) returns (Account);
  rpc Delete(IdRequest) returns (DeleteResponse);
}