syntax = "proto3";

package repository.deposit;

option go_package = "github.com/Suinar/Bank-repository-service/proto/repository/deposit";

import "repository/common/common.proto";

enum DepositStatus {
  DEPOSIT_STATUS_CLOSED = 0;
  DEPOSIT_STATUS_ACTIVE = 1;
  DEPOSIT_STATUS_REJECTED = 2;
}

message Deposit {
  int64 id = 1;
  int64 user_id = 2;
  int64 currency_id = 3;

  int64 amount = 4;
  float interest_rate = 5;

  int32 term_months = 6;

  DepositStatus status = 7;
}

message DepositList {
  repeated Deposit deposits = 1;
}

service DepositRepository {
  rpc GetAll(repository.common.Empty)
      returns (DepositList);

  rpc GetByUser(repository.common.UserIdRequest)
      returns (DepositList);

  rpc GetById(repository.common.IdRequest)
      returns (Deposit);

  rpc Create(Deposit)
      returns (Deposit);

  rpc Replenish(repository.common.AmountRequest)
      returns (Deposit);

  rpc Delete(repository.common.IdRequest)
      returns (repository.common.Empty);
}