// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: repository/deposit/deposit.proto

package __

import (
	context "context"
	common "Bank-repository-service/proto/repository/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DepositRepository_GetAll_FullMethodName    = "/repository.deposit.DepositRepository/GetAll"
	DepositRepository_GetByUser_FullMethodName = "/repository.deposit.DepositRepository/GetByUser"
	DepositRepository_GetById_FullMethodName   = "/repository.deposit.DepositRepository/GetById"
	DepositRepository_Create_FullMethodName    = "/repository.deposit.DepositRepository/Create"
	DepositRepository_Replenish_FullMethodName = "/repository.deposit.DepositRepository/Replenish"
	DepositRepository_Delete_FullMethodName    = "/repository.deposit.DepositRepository/Delete"
)

// DepositRepositoryClient is the client API for DepositRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepositRepositoryClient interface {
	GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DepositList, error)
	GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*DepositList, error)
	GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Deposit, error)
	Create(ctx context.Context, in *DepositCreateInput, opts ...grpc.CallOption) (*Deposit, error)
	Replenish(ctx context.Context, in *common.AmountRequest, opts ...grpc.CallOption) (*Deposit, error)
	Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error)
}

type depositRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositRepositoryClient(cc grpc.ClientConnInterface) DepositRepositoryClient {
	return &depositRepositoryClient{cc}
}

func (c *depositRepositoryClient) GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DepositList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositList)
	err := c.cc.Invoke(ctx, DepositRepository_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositRepositoryClient) GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*DepositList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositList)
	err := c.cc.Invoke(ctx, DepositRepository_GetByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositRepositoryClient) GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Deposit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deposit)
	err := c.cc.Invoke(ctx, DepositRepository_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositRepositoryClient) Create(ctx context.Context, in *DepositCreateInput, opts ...grpc.CallOption) (*Deposit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deposit)
	err := c.cc.Invoke(ctx, DepositRepository_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositRepositoryClient) Replenish(ctx context.Context, in *common.AmountRequest, opts ...grpc.CallOption) (*Deposit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deposit)
	err := c.cc.Invoke(ctx, DepositRepository_Replenish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositRepositoryClient) Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.DeleteResponse)
	err := c.cc.Invoke(ctx, DepositRepository_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositRepositoryServer is the server API for DepositRepository service.
// All implementations must embed UnimplementedDepositRepositoryServer
// for forward compatibility.
type DepositRepositoryServer interface {
	GetAll(context.Context, *common.Empty) (*DepositList, error)
	GetByUser(context.Context, *common.UserIdRequest) (*DepositList, error)
	GetById(context.Context, *common.IdRequest) (*Deposit, error)
	Create(context.Context, *DepositCreateInput) (*Deposit, error)
	Replenish(context.Context, *common.AmountRequest) (*Deposit, error)
	Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error)
	mustEmbedUnimplementedDepositRepositoryServer()
}

// UnimplementedDepositRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepositRepositoryServer struct{}

func (UnimplementedDepositRepositoryServer) GetAll(context.Context, *common.Empty) (*DepositList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedDepositRepositoryServer) GetByUser(context.Context, *common.UserIdRequest) (*DepositList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByUser not implemented")
}
func (UnimplementedDepositRepositoryServer) GetById(context.Context, *common.IdRequest) (*Deposit, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedDepositRepositoryServer) Create(context.Context, *DepositCreateInput) (*Deposit, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDepositRepositoryServer) Replenish(context.Context, *common.AmountRequest) (*Deposit, error) {
	return nil, status.Error(codes.Unimplemented, "method Replenish not implemented")
}
func (UnimplementedDepositRepositoryServer) Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDepositRepositoryServer) mustEmbedUnimplementedDepositRepositoryServer() {}
func (UnimplementedDepositRepositoryServer) testEmbeddedByValue()                           {}

// UnsafeDepositRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepositRepositoryServer will
// result in compilation errors.
type UnsafeDepositRepositoryServer interface {
	mustEmbedUnimplementedDepositRepositoryServer()
}

func RegisterDepositRepositoryServer(s grpc.ServiceRegistrar, srv DepositRepositoryServer) {
	// If the following call panics, it indicates UnimplementedDepositRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepositRepository_ServiceDesc, srv)
}

func _DepositRepository_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositRepositoryServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositRepository_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositRepositoryServer).GetAll(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositRepository_GetByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositRepositoryServer).GetByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositRepository_GetByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositRepositoryServer).GetByUser(ctx, req.(*common.UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositRepository_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositRepositoryServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositRepository_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositRepositoryServer).GetById(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositCreateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositRepository_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositRepositoryServer).Create(ctx, req.(*DepositCreateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositRepository_Replenish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.AmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositRepositoryServer).Replenish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositRepository_Replenish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositRepositoryServer).Replenish(ctx, req.(*common.AmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositRepository_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositRepositoryServer).Delete(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepositRepository_ServiceDesc is the grpc.ServiceDesc for DepositRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepositRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.deposit.DepositRepository",
	HandlerType: (*DepositRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _DepositRepository_GetAll_Handler,
		},
		{
			MethodName: "GetByUser",
			Handler:    _DepositRepository_GetByUser_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _DepositRepository_GetById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DepositRepository_Create_Handler,
		},
		{
			MethodName: "Replenish",
			Handler:    _DepositRepository_Replenish_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DepositRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/deposit/deposit.proto",
}
