// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: repository/deposit/deposit.proto

package __

import (
	common "github.com/Suinar/Bank-repository-service/proto/repository/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositStatus int32

const (
	DepositStatus_DEPOSIT_STATUS_CLOSED   DepositStatus = 0
	DepositStatus_DEPOSIT_STATUS_ACTIVE   DepositStatus = 1
	DepositStatus_DEPOSIT_STATUS_REJECTED DepositStatus = 2
)

// Enum value maps for DepositStatus.
var (
	DepositStatus_name = map[int32]string{
		0: "DEPOSIT_STATUS_CLOSED",
		1: "DEPOSIT_STATUS_ACTIVE",
		2: "DEPOSIT_STATUS_REJECTED",
	}
	DepositStatus_value = map[string]int32{
		"DEPOSIT_STATUS_CLOSED":   0,
		"DEPOSIT_STATUS_ACTIVE":   1,
		"DEPOSIT_STATUS_REJECTED": 2,
	}
)

func (x DepositStatus) Enum() *DepositStatus {
	p := new(DepositStatus)
	*p = x
	return p
}

func (x DepositStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepositStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_deposit_deposit_proto_enumTypes[0].Descriptor()
}

func (DepositStatus) Type() protoreflect.EnumType {
	return &file_repository_deposit_deposit_proto_enumTypes[0]
}

func (x DepositStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepositStatus.Descriptor instead.
func (DepositStatus) EnumDescriptor() ([]byte, []int) {
	return file_repository_deposit_deposit_proto_rawDescGZIP(), []int{0}
}

type Deposit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	InterestRate  float32                `protobuf:"fixed32,5,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	TermMonths    int32                  `protobuf:"varint,6,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	Status        DepositStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=repository.deposit.DepositStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deposit) Reset() {
	*x = Deposit{}
	mi := &file_repository_deposit_deposit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit) ProtoMessage() {}

func (x *Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_repository_deposit_deposit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit.ProtoReflect.Descriptor instead.
func (*Deposit) Descriptor() ([]byte, []int) {
	return file_repository_deposit_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *Deposit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Deposit) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Deposit) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *Deposit) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Deposit) GetInterestRate() float32 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *Deposit) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *Deposit) GetStatus() DepositStatus {
	if x != nil {
		return x.Status
	}
	return DepositStatus_DEPOSIT_STATUS_CLOSED
}

type DepositCreateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,2,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TermMonths    int32                  `protobuf:"varint,4,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositCreateInput) Reset() {
	*x = DepositCreateInput{}
	mi := &file_repository_deposit_deposit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositCreateInput) ProtoMessage() {}

func (x *DepositCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_repository_deposit_deposit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositCreateInput.ProtoReflect.Descriptor instead.
func (*DepositCreateInput) Descriptor() ([]byte, []int) {
	return file_repository_deposit_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *DepositCreateInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DepositCreateInput) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *DepositCreateInput) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositCreateInput) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

type DepositList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deposits      []*Deposit             `protobuf:"bytes,1,rep,name=deposits,proto3" json:"deposits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositList) Reset() {
	*x = DepositList{}
	mi := &file_repository_deposit_deposit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositList) ProtoMessage() {}

func (x *DepositList) ProtoReflect() protoreflect.Message {
	mi := &file_repository_deposit_deposit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositList.ProtoReflect.Descriptor instead.
func (*DepositList) Descriptor() ([]byte, []int) {
	return file_repository_deposit_deposit_proto_rawDescGZIP(), []int{2}
}

func (x *DepositList) GetDeposits() []*Deposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

var File_repository_deposit_deposit_proto protoreflect.FileDescriptor

const file_repository_deposit_deposit_proto_rawDesc = "" +
	"\n" +
	" repository/deposit/deposit.proto\x12\x12repository.deposit\x1a\x17repository/common.proto\"\xec\x01\n" +
	"\aDeposit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcurrency_id\x18\x03 \x01(\x03R\n" +
	"currencyId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12#\n" +
	"\rinterest_rate\x18\x05 \x01(\x02R\finterestRate\x12\x1f\n" +
	"\vterm_months\x18\x06 \x01(\x05R\n" +
	"termMonths\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.repository.deposit.DepositStatusR\x06status\"\x87\x01\n" +
	"\x12DepositCreateInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcurrency_id\x18\x02 \x01(\x03R\n" +
	"currencyId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vterm_months\x18\x04 \x01(\x05R\n" +
	"termMonths\"F\n" +
	"\vDepositList\x127\n" +
	"\bdeposits\x18\x01 \x03(\v2\x1b.repository.deposit.DepositR\bdeposits*b\n" +
	"\rDepositStatus\x12\x19\n" +
	"\x15DEPOSIT_STATUS_CLOSED\x10\x00\x12\x19\n" +
	"\x15DEPOSIT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17DEPOSIT_STATUS_REJECTED\x10\x022\xd4\x03\n" +
	"\x11DepositRepository\x12C\n" +
	"\x06GetAll\x12\x18.repository.common.Empty\x1a\x1f.repository.deposit.DepositList\x12N\n" +
	"\tGetByUser\x12 .repository.common.UserIdRequest\x1a\x1f.repository.deposit.DepositList\x12D\n" +
	"\aGetById\x12\x1c.repository.common.IdRequest\x1a\x1b.repository.deposit.Deposit\x12M\n" +
	"\x06Create\x12&.repository.deposit.DepositCreateInput\x1a\x1b.repository.deposit.Deposit\x12J\n" +
	"\tReplenish\x12 .repository.common.AmountRequest\x1a\x1b.repository.deposit.Deposit\x12I\n" +
	"\x06Delete\x12\x1c.repository.common.IdRequest\x1a!.repository.common.DeleteResponseB\x03Z\x01/b\x06proto3"

var (
	file_repository_deposit_deposit_proto_rawDescOnce sync.Once
	file_repository_deposit_deposit_proto_rawDescData []byte
)

func file_repository_deposit_deposit_proto_rawDescGZIP() []byte {
	file_repository_deposit_deposit_proto_rawDescOnce.Do(func() {
		file_repository_deposit_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_deposit_deposit_proto_rawDesc), len(file_repository_deposit_deposit_proto_rawDesc)))
	})
	return file_repository_deposit_deposit_proto_rawDescData
}

var file_repository_deposit_deposit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repository_deposit_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_repository_deposit_deposit_proto_goTypes = []any{
	(DepositStatus)(0),            // 0: repository.deposit.DepositStatus
	(*Deposit)(nil),               // 1: repository.deposit.Deposit
	(*DepositCreateInput)(nil),    // 2: repository.deposit.DepositCreateInput
	(*DepositList)(nil),           // 3: repository.deposit.DepositList
	(*common.Empty)(nil),          // 4: repository.common.Empty
	(*common.UserIdRequest)(nil),  // 5: repository.common.UserIdRequest
	(*common.IdRequest)(nil),      // 6: repository.common.IdRequest
	(*common.AmountRequest)(nil),  // 7: repository.common.AmountRequest
	(*common.DeleteResponse)(nil), // 8: repository.common.DeleteResponse
}
var file_repository_deposit_deposit_proto_depIdxs = []int32{
	0, // 0: repository.deposit.Deposit.status:type_name -> repository.deposit.DepositStatus
	1, // 1: repository.deposit.DepositList.deposits:type_name -> repository.deposit.Deposit
	4, // 2: repository.deposit.DepositRepository.GetAll:input_type -> repository.common.Empty
	5, // 3: repository.deposit.DepositRepository.GetByUser:input_type -> repository.common.UserIdRequest
	6, // 4: repository.deposit.DepositRepository.GetById:input_type -> repository.common.IdRequest
	2, // 5: repository.deposit.DepositRepository.Create:input_type -> repository.deposit.DepositCreateInput
	7, // 6: repository.deposit.DepositRepository.Replenish:input_type -> repository.common.AmountRequest
	6, // 7: repository.deposit.DepositRepository.Delete:input_type -> repository.common.IdRequest
	3, // 8: repository.deposit.DepositRepository.GetAll:output_type -> repository.deposit.DepositList
	3, // 9: repository.deposit.DepositRepository.GetByUser:output_type -> repository.deposit.DepositList
	1, // 10: repository.deposit.DepositRepository.GetById:output_type -> repository.deposit.Deposit
	1, // 11: repository.deposit.DepositRepository.Create:output_type -> repository.deposit.Deposit
	1, // 12: repository.deposit.DepositRepository.Replenish:output_type -> repository.deposit.Deposit
	8, // 13: repository.deposit.DepositRepository.Delete:output_type -> repository.common.DeleteResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_repository_deposit_deposit_proto_init() }
func file_repository_deposit_deposit_proto_init() {
	if File_repository_deposit_deposit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_deposit_deposit_proto_rawDesc), len(file_repository_deposit_deposit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_deposit_deposit_proto_goTypes,
		DependencyIndexes: file_repository_deposit_deposit_proto_depIdxs,
		EnumInfos:         file_repository_deposit_deposit_proto_enumTypes,
		MessageInfos:      file_repository_deposit_deposit_proto_msgTypes,
	}.Build()
	File_repository_deposit_deposit_proto = out.File
	file_repository_deposit_deposit_proto_goTypes = nil
	file_repository_deposit_deposit_proto_depIdxs = nil
}
