// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: repository/credit/credit.proto

package __

import (
	common "Bank-repository-service/proto/repository/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditStatus int32

const (
	CreditStatus_CREDIT_STATUS_CLOSED   CreditStatus = 0
	CreditStatus_CREDIT_STATUS_ACTIVE   CreditStatus = 1
	CreditStatus_CREDIT_STATUS_REJECTED CreditStatus = 2
)

// Enum value maps for CreditStatus.
var (
	CreditStatus_name = map[int32]string{
		0: "CREDIT_STATUS_CLOSED",
		1: "CREDIT_STATUS_ACTIVE",
		2: "CREDIT_STATUS_REJECTED",
	}
	CreditStatus_value = map[string]int32{
		"CREDIT_STATUS_CLOSED":   0,
		"CREDIT_STATUS_ACTIVE":   1,
		"CREDIT_STATUS_REJECTED": 2,
	}
)

func (x CreditStatus) Enum() *CreditStatus {
	p := new(CreditStatus)
	*p = x
	return p
}

func (x CreditStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreditStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_credit_credit_proto_enumTypes[0].Descriptor()
}

func (CreditStatus) Type() protoreflect.EnumType {
	return &file_repository_credit_credit_proto_enumTypes[0]
}

func (x CreditStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreditStatus.Descriptor instead.
func (CreditStatus) EnumDescriptor() ([]byte, []int) {
	return file_repository_credit_credit_proto_rawDescGZIP(), []int{0}
}

type Credit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyId     int64                  `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	InterestRate   float32                `protobuf:"fixed32,5,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	TermMonths     int32                  `protobuf:"varint,6,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MonthlyPayment int64                  `protobuf:"varint,7,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	Status         CreditStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=repository.credit.CreditStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Credit) Reset() {
	*x = Credit{}
	mi := &file_repository_credit_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credit) ProtoMessage() {}

func (x *Credit) ProtoReflect() protoreflect.Message {
	mi := &file_repository_credit_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credit.ProtoReflect.Descriptor instead.
func (*Credit) Descriptor() ([]byte, []int) {
	return file_repository_credit_credit_proto_rawDescGZIP(), []int{0}
}

func (x *Credit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Credit) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Credit) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *Credit) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Credit) GetInterestRate() float32 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *Credit) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *Credit) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *Credit) GetStatus() CreditStatus {
	if x != nil {
		return x.Status
	}
	return CreditStatus_CREDIT_STATUS_CLOSED
}

type CreditCreateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,2,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TermMonths    int32                  `protobuf:"varint,4,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditCreateInput) Reset() {
	*x = CreditCreateInput{}
	mi := &file_repository_credit_credit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCreateInput) ProtoMessage() {}

func (x *CreditCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_repository_credit_credit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCreateInput.ProtoReflect.Descriptor instead.
func (*CreditCreateInput) Descriptor() ([]byte, []int) {
	return file_repository_credit_credit_proto_rawDescGZIP(), []int{1}
}

func (x *CreditCreateInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreditCreateInput) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *CreditCreateInput) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreditCreateInput) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

type CreditList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credits       []*Credit              `protobuf:"bytes,1,rep,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditList) Reset() {
	*x = CreditList{}
	mi := &file_repository_credit_credit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditList) ProtoMessage() {}

func (x *CreditList) ProtoReflect() protoreflect.Message {
	mi := &file_repository_credit_credit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditList.ProtoReflect.Descriptor instead.
func (*CreditList) Descriptor() ([]byte, []int) {
	return file_repository_credit_credit_proto_rawDescGZIP(), []int{2}
}

func (x *CreditList) GetCredits() []*Credit {
	if x != nil {
		return x.Credits
	}
	return nil
}

var File_repository_credit_credit_proto protoreflect.FileDescriptor

const file_repository_credit_credit_proto_rawDesc = "" +
	"\n" +
	"\x1erepository/credit/credit.proto\x12\x11repository.credit\x1a\x17repository/common.proto\"\x92\x02\n" +
	"\x06Credit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcurrency_id\x18\x03 \x01(\x03R\n" +
	"currencyId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12#\n" +
	"\rinterest_rate\x18\x05 \x01(\x02R\finterestRate\x12\x1f\n" +
	"\vterm_months\x18\x06 \x01(\x05R\n" +
	"termMonths\x12'\n" +
	"\x0fmonthly_payment\x18\a \x01(\x03R\x0emonthlyPayment\x127\n" +
	"\x06status\x18\b \x01(\x0e2\x1f.repository.credit.CreditStatusR\x06status\"\x86\x01\n" +
	"\x11CreditCreateInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcurrency_id\x18\x02 \x01(\x03R\n" +
	"currencyId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vterm_months\x18\x04 \x01(\x05R\n" +
	"termMonths\"A\n" +
	"\n" +
	"CreditList\x123\n" +
	"\acredits\x18\x01 \x03(\v2\x19.repository.credit.CreditR\acredits*^\n" +
	"\fCreditStatus\x12\x18\n" +
	"\x14CREDIT_STATUS_CLOSED\x10\x00\x12\x18\n" +
	"\x14CREDIT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16CREDIT_STATUS_REJECTED\x10\x022\xf8\x02\n" +
	"\x10CreditRepository\x12A\n" +
	"\x06GetAll\x12\x18.repository.common.Empty\x1a\x1d.repository.credit.CreditList\x12L\n" +
	"\tGetByUser\x12 .repository.common.UserIdRequest\x1a\x1d.repository.credit.CreditList\x12B\n" +
	"\aGetById\x12\x1c.repository.common.IdRequest\x1a\x19.repository.credit.Credit\x12D\n" +
	"\x05Repay\x12 .repository.common.AmountRequest\x1a\x19.repository.credit.Credit\x12I\n" +
	"\x06Delete\x12\x1c.repository.common.IdRequest\x1a!.repository.common.DeleteResponseB\x03Z\x01/b\x06proto3"

var (
	file_repository_credit_credit_proto_rawDescOnce sync.Once
	file_repository_credit_credit_proto_rawDescData []byte
)

func file_repository_credit_credit_proto_rawDescGZIP() []byte {
	file_repository_credit_credit_proto_rawDescOnce.Do(func() {
		file_repository_credit_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_credit_credit_proto_rawDesc), len(file_repository_credit_credit_proto_rawDesc)))
	})
	return file_repository_credit_credit_proto_rawDescData
}

var file_repository_credit_credit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repository_credit_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_repository_credit_credit_proto_goTypes = []any{
	(CreditStatus)(0),             // 0: repository.credit.CreditStatus
	(*Credit)(nil),                // 1: repository.credit.Credit
	(*CreditCreateInput)(nil),     // 2: repository.credit.CreditCreateInput
	(*CreditList)(nil),            // 3: repository.credit.CreditList
	(*common.Empty)(nil),          // 4: repository.common.Empty
	(*common.UserIdRequest)(nil),  // 5: repository.common.UserIdRequest
	(*common.IdRequest)(nil),      // 6: repository.common.IdRequest
	(*common.AmountRequest)(nil),  // 7: repository.common.AmountRequest
	(*common.DeleteResponse)(nil), // 8: repository.common.DeleteResponse
}
var file_repository_credit_credit_proto_depIdxs = []int32{
	0, // 0: repository.credit.Credit.status:type_name -> repository.credit.CreditStatus
	1, // 1: repository.credit.CreditList.credits:type_name -> repository.credit.Credit
	4, // 2: repository.credit.CreditRepository.GetAll:input_type -> repository.common.Empty
	5, // 3: repository.credit.CreditRepository.GetByUser:input_type -> repository.common.UserIdRequest
	6, // 4: repository.credit.CreditRepository.GetById:input_type -> repository.common.IdRequest
	7, // 5: repository.credit.CreditRepository.Repay:input_type -> repository.common.AmountRequest
	6, // 6: repository.credit.CreditRepository.Delete:input_type -> repository.common.IdRequest
	3, // 7: repository.credit.CreditRepository.GetAll:output_type -> repository.credit.CreditList
	3, // 8: repository.credit.CreditRepository.GetByUser:output_type -> repository.credit.CreditList
	1, // 9: repository.credit.CreditRepository.GetById:output_type -> repository.credit.Credit
	1, // 10: repository.credit.CreditRepository.Repay:output_type -> repository.credit.Credit
	8, // 11: repository.credit.CreditRepository.Delete:output_type -> repository.common.DeleteResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_repository_credit_credit_proto_init() }
func file_repository_credit_credit_proto_init() {
	if File_repository_credit_credit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_credit_credit_proto_rawDesc), len(file_repository_credit_credit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_credit_credit_proto_goTypes,
		DependencyIndexes: file_repository_credit_credit_proto_depIdxs,
		EnumInfos:         file_repository_credit_credit_proto_enumTypes,
		MessageInfos:      file_repository_credit_credit_proto_msgTypes,
	}.Build()
	File_repository_credit_credit_proto = out.File
	file_repository_credit_credit_proto_goTypes = nil
	file_repository_credit_credit_proto_depIdxs = nil
}
