// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: repository/credit/credit.proto

package credit

import (
	context "context"
	common "Bank-repository-service/proto/repository/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreditRepository_GetAll_FullMethodName    = "/repository.credit.CreditRepository/GetAll"
	CreditRepository_GetByUser_FullMethodName = "/repository.credit.CreditRepository/GetByUser"
	CreditRepository_GetById_FullMethodName   = "/repository.credit.CreditRepository/GetById"
	CreditRepository_Create_FullMethodName    = "/repository.credit.CreditRepository/Create"
	CreditRepository_Repay_FullMethodName     = "/repository.credit.CreditRepository/Repay"
	CreditRepository_Delete_FullMethodName    = "/repository.credit.CreditRepository/Delete"
)

// CreditRepositoryClient is the client API for CreditRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreditRepositoryClient interface {
	GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CreditList, error)
	GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*CreditList, error)
	GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Credit, error)
	Create(ctx context.Context, in *Credit, opts ...grpc.CallOption) (*Credit, error)
	Repay(ctx context.Context, in *common.AmountRequest, opts ...grpc.CallOption) (*Credit, error)
	Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error)
}

type creditRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewCreditRepositoryClient(cc grpc.ClientConnInterface) CreditRepositoryClient {
	return &creditRepositoryClient{cc}
}

func (c *creditRepositoryClient) GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CreditList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditList)
	err := c.cc.Invoke(ctx, CreditRepository_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditRepositoryClient) GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*CreditList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditList)
	err := c.cc.Invoke(ctx, CreditRepository_GetByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditRepositoryClient) GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Credit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Credit)
	err := c.cc.Invoke(ctx, CreditRepository_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditRepositoryClient) Create(ctx context.Context, in *Credit, opts ...grpc.CallOption) (*Credit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Credit)
	err := c.cc.Invoke(ctx, CreditRepository_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditRepositoryClient) Repay(ctx context.Context, in *common.AmountRequest, opts ...grpc.CallOption) (*Credit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Credit)
	err := c.cc.Invoke(ctx, CreditRepository_Repay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditRepositoryClient) Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.DeleteResponse)
	err := c.cc.Invoke(ctx, CreditRepository_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditRepositoryServer is the server API for CreditRepository service.
// All implementations must embed UnimplementedCreditRepositoryServer
// for forward compatibility.
type CreditRepositoryServer interface {
	GetAll(context.Context, *common.Empty) (*CreditList, error)
	GetByUser(context.Context, *common.UserIdRequest) (*CreditList, error)
	GetById(context.Context, *common.IdRequest) (*Credit, error)
	Create(context.Context, *Credit) (*Credit, error)
	Repay(context.Context, *common.AmountRequest) (*Credit, error)
	Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error)
	mustEmbedUnimplementedCreditRepositoryServer()
}

// UnimplementedCreditRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreditRepositoryServer struct{}

func (UnimplementedCreditRepositoryServer) GetAll(context.Context, *common.Empty) (*CreditList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCreditRepositoryServer) GetByUser(context.Context, *common.UserIdRequest) (*CreditList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByUser not implemented")
}
func (UnimplementedCreditRepositoryServer) GetById(context.Context, *common.IdRequest) (*Credit, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedCreditRepositoryServer) Create(context.Context, *Credit) (*Credit, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCreditRepositoryServer) Repay(context.Context, *common.AmountRequest) (*Credit, error) {
	return nil, status.Error(codes.Unimplemented, "method Repay not implemented")
}
func (UnimplementedCreditRepositoryServer) Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCreditRepositoryServer) mustEmbedUnimplementedCreditRepositoryServer() {}
func (UnimplementedCreditRepositoryServer) testEmbeddedByValue()                          {}

// UnsafeCreditRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreditRepositoryServer will
// result in compilation errors.
type UnsafeCreditRepositoryServer interface {
	mustEmbedUnimplementedCreditRepositoryServer()
}

func RegisterCreditRepositoryServer(s grpc.ServiceRegistrar, srv CreditRepositoryServer) {
	// If the following call panics, it indicates UnimplementedCreditRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreditRepository_ServiceDesc, srv)
}

func _CreditRepository_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditRepositoryServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditRepository_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditRepositoryServer).GetAll(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditRepository_GetByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditRepositoryServer).GetByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditRepository_GetByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditRepositoryServer).GetByUser(ctx, req.(*common.UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditRepository_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditRepositoryServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditRepository_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditRepositoryServer).GetById(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditRepository_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditRepositoryServer).Create(ctx, req.(*Credit))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditRepository_Repay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.AmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditRepositoryServer).Repay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditRepository_Repay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditRepositoryServer).Repay(ctx, req.(*common.AmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditRepository_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditRepositoryServer).Delete(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreditRepository_ServiceDesc is the grpc.ServiceDesc for CreditRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreditRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.credit.CreditRepository",
	HandlerType: (*CreditRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _CreditRepository_GetAll_Handler,
		},
		{
			MethodName: "GetByUser",
			Handler:    _CreditRepository_GetByUser_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _CreditRepository_GetById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CreditRepository_Create_Handler,
		},
		{
			MethodName: "Repay",
			Handler:    _CreditRepository_Repay_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CreditRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/credit/credit.proto",
}
