syntax = "proto3";

package repository.credit;

option go_package = "github.com/Suinar/Bank-repository-service/proto/repository/credit";

import "repository/common/common.proto";

enum CreditStatus {
  CREDIT_STATUS_CLOSED = 0;
  CREDIT_STATUS_ACTIVE = 1;
  CREDIT_STATUS_REJECTED = 2;
}

message Credit {
  int64 id = 1;
  int64 user_id = 2;
  int64 currency_id = 3;

  int64 amount = 4;
  float interest_rate = 5;

  int32 term_months = 6;
  int64 monthly_payment = 7;

  CreditStatus status = 8;
}

message CreditCreateInput {
  int64 user_id = 1;
  int64 currency_id = 2;

  int64 amount = 3;
  int32 term_months = 4;
}

message CreditList {
  repeated Credit credits = 1;
}

service CreditRepository {
  rpc GetAll(repository.common.Empty)
      returns (CreditList);

  rpc GetByUser(repository.common.UserIdRequest)
      returns (CreditList);

  rpc GetById(repository.common.IdRequest)
      returns (Credit);

  rpc Create(Credit)
      returns (Credit);

  rpc Repay(repository.common.AmountRequest)
      returns (Credit);

  rpc Delete(repository.common.IdRequest)
      returns (repository.common.Empty);
}