// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: repository/user/user.proto

package user

import (
	common "Bank-repository-service/proto/repository/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_repository_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_repository_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PhoneNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneNumberRequest) Reset() {
	*x = PhoneNumberRequest{}
	mi := &file_repository_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumberRequest) ProtoMessage() {}

func (x *PhoneNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumberRequest.ProtoReflect.Descriptor instead.
func (*PhoneNumberRequest) Descriptor() ([]byte, []int) {
	return file_repository_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneNumberRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_repository_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_repository_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *ChangePasswordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName    *string                `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3,oneof" json:"middle_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,7,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_repository_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_repository_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_repository_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UserUpdateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	MiddleName    *string                `protobuf:"bytes,2,opt,name=middle_name,json=middleName,proto3,oneof" json:"middle_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateInput) Reset() {
	*x = UserUpdateInput{}
	mi := &file_repository_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateInput) ProtoMessage() {}

func (x *UserUpdateInput) ProtoReflect() protoreflect.Message {
	mi := &file_repository_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateInput.ProtoReflect.Descriptor instead.
func (*UserUpdateInput) Descriptor() ([]byte, []int) {
	return file_repository_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserUpdateInput) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UserUpdateInput) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *UserUpdateInput) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         *UserUpdateInput       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_repository_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_repository_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetInput() *UserUpdateInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_repository_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_repository_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_repository_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserList) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_repository_user_user_proto protoreflect.FileDescriptor

const file_repository_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1arepository/user/user.proto\x12\x0frepository.user\x1a\x1erepository/common/common.proto\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"7\n" +
	"\x12PhoneNumberRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"J\n" +
	"\x15ChangePasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\xe6\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12$\n" +
	"\vmiddle_name\x18\x03 \x01(\tH\x00R\n" +
	"middleName\x88\x01\x01\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12#\n" +
	"\rpassword_hash\x18\a \x01(\tR\fpasswordHashB\x0e\n" +
	"\f_middle_name\"\xaa\x01\n" +
	"\x0fUserUpdateInput\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12$\n" +
	"\vmiddle_name\x18\x02 \x01(\tH\x01R\n" +
	"middleName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x02R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\x0e\n" +
	"\f_middle_nameB\f\n" +
	"\n" +
	"_last_name\"[\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x126\n" +
	"\x05input\x18\x02 \x01(\v2 .repository.user.UserUpdateInputR\x05input\"7\n" +
	"\bUserList\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.repository.user.UserR\x05users2\xb6\x04\n" +
	"\x0eUserRepository\x12=\n" +
	"\x06GetAll\x12\x18.repository.common.Empty\x1a\x19.repository.user.UserList\x12>\n" +
	"\aGetById\x12\x1c.repository.common.IdRequest\x1a\x15.repository.user.User\x12B\n" +
	"\n" +
	"GetByEmail\x12\x1d.repository.user.EmailRequest\x1a\x15.repository.user.User\x12N\n" +
	"\x10GetByPhoneNumber\x12#.repository.user.PhoneNumberRequest\x1a\x15.repository.user.User\x126\n" +
	"\x06Create\x12\x15.repository.user.User\x1a\x15.repository.user.User\x12R\n" +
	"\x0eChangePassword\x12&.repository.user.ChangePasswordRequest\x1a\x18.repository.common.Empty\x12C\n" +
	"\x06Update\x12\".repository.user.UpdateUserRequest\x1a\x15.repository.user.User\x12@\n" +
	"\x06Delete\x12\x1c.repository.common.IdRequest\x1a\x18.repository.common.EmptyBAZ?github.com/Suinar/Bank-repository-service/proto/repository/userb\x06proto3"

var (
	file_repository_user_user_proto_rawDescOnce sync.Once
	file_repository_user_user_proto_rawDescData []byte
)

func file_repository_user_user_proto_rawDescGZIP() []byte {
	file_repository_user_user_proto_rawDescOnce.Do(func() {
		file_repository_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_user_user_proto_rawDesc), len(file_repository_user_user_proto_rawDesc)))
	})
	return file_repository_user_user_proto_rawDescData
}

var file_repository_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_repository_user_user_proto_goTypes = []any{
	(*EmailRequest)(nil),          // 0: repository.user.EmailRequest
	(*PhoneNumberRequest)(nil),    // 1: repository.user.PhoneNumberRequest
	(*ChangePasswordRequest)(nil), // 2: repository.user.ChangePasswordRequest
	(*User)(nil),                  // 3: repository.user.User
	(*UserUpdateInput)(nil),       // 4: repository.user.UserUpdateInput
	(*UpdateUserRequest)(nil),     // 5: repository.user.UpdateUserRequest
	(*UserList)(nil),              // 6: repository.user.UserList
	(*common.Empty)(nil),          // 7: repository.common.Empty
	(*common.IdRequest)(nil),      // 8: repository.common.IdRequest
}
var file_repository_user_user_proto_depIdxs = []int32{
	4,  // 0: repository.user.UpdateUserRequest.input:type_name -> repository.user.UserUpdateInput
	3,  // 1: repository.user.UserList.users:type_name -> repository.user.User
	7,  // 2: repository.user.UserRepository.GetAll:input_type -> repository.common.Empty
	8,  // 3: repository.user.UserRepository.GetById:input_type -> repository.common.IdRequest
	0,  // 4: repository.user.UserRepository.GetByEmail:input_type -> repository.user.EmailRequest
	1,  // 5: repository.user.UserRepository.GetByPhoneNumber:input_type -> repository.user.PhoneNumberRequest
	3,  // 6: repository.user.UserRepository.Create:input_type -> repository.user.User
	2,  // 7: repository.user.UserRepository.ChangePassword:input_type -> repository.user.ChangePasswordRequest
	5,  // 8: repository.user.UserRepository.Update:input_type -> repository.user.UpdateUserRequest
	8,  // 9: repository.user.UserRepository.Delete:input_type -> repository.common.IdRequest
	6,  // 10: repository.user.UserRepository.GetAll:output_type -> repository.user.UserList
	3,  // 11: repository.user.UserRepository.GetById:output_type -> repository.user.User
	3,  // 12: repository.user.UserRepository.GetByEmail:output_type -> repository.user.User
	3,  // 13: repository.user.UserRepository.GetByPhoneNumber:output_type -> repository.user.User
	3,  // 14: repository.user.UserRepository.Create:output_type -> repository.user.User
	7,  // 15: repository.user.UserRepository.ChangePassword:output_type -> repository.common.Empty
	3,  // 16: repository.user.UserRepository.Update:output_type -> repository.user.User
	7,  // 17: repository.user.UserRepository.Delete:output_type -> repository.common.Empty
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_repository_user_user_proto_init() }
func file_repository_user_user_proto_init() {
	if File_repository_user_user_proto != nil {
		return
	}
	file_repository_user_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_repository_user_user_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_user_user_proto_rawDesc), len(file_repository_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_user_user_proto_goTypes,
		DependencyIndexes: file_repository_user_user_proto_depIdxs,
		MessageInfos:      file_repository_user_user_proto_msgTypes,
	}.Build()
	File_repository_user_user_proto = out.File
	file_repository_user_user_proto_goTypes = nil
	file_repository_user_user_proto_depIdxs = nil
}
