// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: repository/user/user.proto

package __

import (
	context "context"
	common "Bank-repository-service/proto/repository/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRepository_GetAll_FullMethodName           = "/repository.user.UserRepository/GetAll"
	UserRepository_GetById_FullMethodName          = "/repository.user.UserRepository/GetById"
	UserRepository_GetByEmail_FullMethodName       = "/repository.user.UserRepository/GetByEmail"
	UserRepository_GetByPhoneNumber_FullMethodName = "/repository.user.UserRepository/GetByPhoneNumber"
	UserRepository_Create_FullMethodName           = "/repository.user.UserRepository/Create"
	UserRepository_ChangePassword_FullMethodName   = "/repository.user.UserRepository/ChangePassword"
	UserRepository_Update_FullMethodName           = "/repository.user.UserRepository/Update"
	UserRepository_Delete_FullMethodName           = "/repository.user.UserRepository/Delete"
)

// UserRepositoryClient is the client API for UserRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRepositoryClient interface {
	GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UserList, error)
	GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*User, error)
	GetByEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*User, error)
	GetByPhoneNumber(ctx context.Context, in *PhoneNumberRequest, opts ...grpc.CallOption) (*User, error)
	Create(ctx context.Context, in *UserCreateInput, opts ...grpc.CallOption) (*User, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*common.Empty, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type userRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRepositoryClient(cc grpc.ClientConnInterface) UserRepositoryClient {
	return &userRepositoryClient{cc}
}

func (c *userRepositoryClient) GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserList)
	err := c.cc.Invoke(ctx, UserRepository_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserRepository_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) GetByEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserRepository_GetByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) GetByPhoneNumber(ctx context.Context, in *PhoneNumberRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserRepository_GetByPhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) Create(ctx context.Context, in *UserCreateInput, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserRepository_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, UserRepository_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserRepository_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, UserRepository_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRepositoryServer is the server API for UserRepository service.
// All implementations must embed UnimplementedUserRepositoryServer
// for forward compatibility.
type UserRepositoryServer interface {
	GetAll(context.Context, *common.Empty) (*UserList, error)
	GetById(context.Context, *common.IdRequest) (*User, error)
	GetByEmail(context.Context, *EmailRequest) (*User, error)
	GetByPhoneNumber(context.Context, *PhoneNumberRequest) (*User, error)
	Create(context.Context, *UserCreateInput) (*User, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*common.Empty, error)
	Update(context.Context, *UpdateUserRequest) (*User, error)
	Delete(context.Context, *common.IdRequest) (*common.Empty, error)
	mustEmbedUnimplementedUserRepositoryServer()
}

// UnimplementedUserRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRepositoryServer struct{}

func (UnimplementedUserRepositoryServer) GetAll(context.Context, *common.Empty) (*UserList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedUserRepositoryServer) GetById(context.Context, *common.IdRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedUserRepositoryServer) GetByEmail(context.Context, *EmailRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByEmail not implemented")
}
func (UnimplementedUserRepositoryServer) GetByPhoneNumber(context.Context, *PhoneNumberRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByPhoneNumber not implemented")
}
func (UnimplementedUserRepositoryServer) Create(context.Context, *UserCreateInput) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserRepositoryServer) ChangePassword(context.Context, *ChangePasswordRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedUserRepositoryServer) Update(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserRepositoryServer) Delete(context.Context, *common.IdRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserRepositoryServer) mustEmbedUnimplementedUserRepositoryServer() {}
func (UnimplementedUserRepositoryServer) testEmbeddedByValue()                        {}

// UnsafeUserRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRepositoryServer will
// result in compilation errors.
type UnsafeUserRepositoryServer interface {
	mustEmbedUnimplementedUserRepositoryServer()
}

func RegisterUserRepositoryServer(s grpc.ServiceRegistrar, srv UserRepositoryServer) {
	// If the following call panics, it indicates UnimplementedUserRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRepository_ServiceDesc, srv)
}

func _UserRepository_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).GetAll(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).GetById(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_GetByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).GetByEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_GetByPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).GetByPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_GetByPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).GetByPhoneNumber(ctx, req.(*PhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).Create(ctx, req.(*UserCreateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRepository_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).Delete(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRepository_ServiceDesc is the grpc.ServiceDesc for UserRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.user.UserRepository",
	HandlerType: (*UserRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _UserRepository_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _UserRepository_GetById_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _UserRepository_GetByEmail_Handler,
		},
		{
			MethodName: "GetByPhoneNumber",
			Handler:    _UserRepository_GetByPhoneNumber_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserRepository_Create_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserRepository_ChangePassword_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserRepository_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/user/user.proto",
}
