syntax = "proto3";

package repository.currency;

option go_package = "github.com/Suinar/Bank-repository-service/proto/repository/currency";

import "repository/common/common.proto";

message IsoCodeRequest {
  string iso_code = 1;
}

message SymbolRequest {
  string symbol = 1;
}

message Currency {
  int64 id = 1;

  string name = 2;

  string symbol = 3;
  string iso_code = 4;

  int32 minor_units = 5;
}

message CurrencyUpdateInput {
  optional string name = 1;

  optional string symbol = 2;
  optional string iso_code = 3;

  optional int32 minor_units = 4;
}

message CurrencyList {
  repeated Currency currencies = 1;
}

message UpdateCurrencyRequest {
  int64 id = 1;
  CurrencyUpdateInput input = 2;
}

service CurrencyRepository {
  rpc GetAll(repository.common.Empty)
      returns (CurrencyList);

  rpc GetById(repository.common.IdRequest)
      returns (Currency);

  rpc GetByIso(IsoCodeRequest)
      returns (Currency);

  rpc GetBySymbol(SymbolRequest)
      returns (Currency);

  rpc Create(Currency)
      returns (Currency);

  rpc Update(UpdateCurrencyRequest)
      returns (Currency);

  rpc Delete(repository.common.IdRequest)
      returns (repository.common.DeleteResponse);
}