// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: repository/currency/currency.proto

package __

import (
	context "context"
	common "Bank-repository-service/proto/repository/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyRepository_GetAll_FullMethodName      = "/repository.currency.CurrencyRepository/GetAll"
	CurrencyRepository_GetById_FullMethodName     = "/repository.currency.CurrencyRepository/GetById"
	CurrencyRepository_GetByIso_FullMethodName    = "/repository.currency.CurrencyRepository/GetByIso"
	CurrencyRepository_GetBySymbol_FullMethodName = "/repository.currency.CurrencyRepository/GetBySymbol"
	CurrencyRepository_Create_FullMethodName      = "/repository.currency.CurrencyRepository/Create"
	CurrencyRepository_Update_FullMethodName      = "/repository.currency.CurrencyRepository/Update"
	CurrencyRepository_Delete_FullMethodName      = "/repository.currency.CurrencyRepository/Delete"
)

// CurrencyRepositoryClient is the client API for CurrencyRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyRepositoryClient interface {
	GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CurrencyList, error)
	GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Currency, error)
	GetByIso(ctx context.Context, in *IsoCodeRequest, opts ...grpc.CallOption) (*Currency, error)
	GetBySymbol(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (*Currency, error)
	Create(ctx context.Context, in *CurrencyCreateInput, opts ...grpc.CallOption) (*Currency, error)
	Update(ctx context.Context, in *UpdateCurrencyRequest, opts ...grpc.CallOption) (*Currency, error)
	Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error)
}

type currencyRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyRepositoryClient(cc grpc.ClientConnInterface) CurrencyRepositoryClient {
	return &currencyRepositoryClient{cc}
}

func (c *currencyRepositoryClient) GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CurrencyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrencyList)
	err := c.cc.Invoke(ctx, CurrencyRepository_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRepositoryClient) GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Currency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Currency)
	err := c.cc.Invoke(ctx, CurrencyRepository_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRepositoryClient) GetByIso(ctx context.Context, in *IsoCodeRequest, opts ...grpc.CallOption) (*Currency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Currency)
	err := c.cc.Invoke(ctx, CurrencyRepository_GetByIso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRepositoryClient) GetBySymbol(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (*Currency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Currency)
	err := c.cc.Invoke(ctx, CurrencyRepository_GetBySymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRepositoryClient) Create(ctx context.Context, in *CurrencyCreateInput, opts ...grpc.CallOption) (*Currency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Currency)
	err := c.cc.Invoke(ctx, CurrencyRepository_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRepositoryClient) Update(ctx context.Context, in *UpdateCurrencyRequest, opts ...grpc.CallOption) (*Currency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Currency)
	err := c.cc.Invoke(ctx, CurrencyRepository_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyRepositoryClient) Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.DeleteResponse)
	err := c.cc.Invoke(ctx, CurrencyRepository_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyRepositoryServer is the server API for CurrencyRepository service.
// All implementations must embed UnimplementedCurrencyRepositoryServer
// for forward compatibility.
type CurrencyRepositoryServer interface {
	GetAll(context.Context, *common.Empty) (*CurrencyList, error)
	GetById(context.Context, *common.IdRequest) (*Currency, error)
	GetByIso(context.Context, *IsoCodeRequest) (*Currency, error)
	GetBySymbol(context.Context, *SymbolRequest) (*Currency, error)
	Create(context.Context, *CurrencyCreateInput) (*Currency, error)
	Update(context.Context, *UpdateCurrencyRequest) (*Currency, error)
	Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error)
	mustEmbedUnimplementedCurrencyRepositoryServer()
}

// UnimplementedCurrencyRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyRepositoryServer struct{}

func (UnimplementedCurrencyRepositoryServer) GetAll(context.Context, *common.Empty) (*CurrencyList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCurrencyRepositoryServer) GetById(context.Context, *common.IdRequest) (*Currency, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedCurrencyRepositoryServer) GetByIso(context.Context, *IsoCodeRequest) (*Currency, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByIso not implemented")
}
func (UnimplementedCurrencyRepositoryServer) GetBySymbol(context.Context, *SymbolRequest) (*Currency, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBySymbol not implemented")
}
func (UnimplementedCurrencyRepositoryServer) Create(context.Context, *CurrencyCreateInput) (*Currency, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCurrencyRepositoryServer) Update(context.Context, *UpdateCurrencyRequest) (*Currency, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCurrencyRepositoryServer) Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCurrencyRepositoryServer) mustEmbedUnimplementedCurrencyRepositoryServer() {}
func (UnimplementedCurrencyRepositoryServer) testEmbeddedByValue()                            {}

// UnsafeCurrencyRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyRepositoryServer will
// result in compilation errors.
type UnsafeCurrencyRepositoryServer interface {
	mustEmbedUnimplementedCurrencyRepositoryServer()
}

func RegisterCurrencyRepositoryServer(s grpc.ServiceRegistrar, srv CurrencyRepositoryServer) {
	// If the following call panics, it indicates UnimplementedCurrencyRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyRepository_ServiceDesc, srv)
}

func _CurrencyRepository_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRepositoryServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRepository_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRepositoryServer).GetAll(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRepository_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRepositoryServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRepository_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRepositoryServer).GetById(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRepository_GetByIso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsoCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRepositoryServer).GetByIso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRepository_GetByIso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRepositoryServer).GetByIso(ctx, req.(*IsoCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRepository_GetBySymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRepositoryServer).GetBySymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRepository_GetBySymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRepositoryServer).GetBySymbol(ctx, req.(*SymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyCreateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRepository_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRepositoryServer).Create(ctx, req.(*CurrencyCreateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRepository_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRepositoryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRepository_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRepositoryServer).Update(ctx, req.(*UpdateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyRepository_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyRepositoryServer).Delete(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyRepository_ServiceDesc is the grpc.ServiceDesc for CurrencyRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.currency.CurrencyRepository",
	HandlerType: (*CurrencyRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _CurrencyRepository_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _CurrencyRepository_GetById_Handler,
		},
		{
			MethodName: "GetByIso",
			Handler:    _CurrencyRepository_GetByIso_Handler,
		},
		{
			MethodName: "GetBySymbol",
			Handler:    _CurrencyRepository_GetBySymbol_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CurrencyRepository_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CurrencyRepository_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CurrencyRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/currency/currency.proto",
}
