// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	card "github.com/Suinar/Bank-proto/repository/card"
	common "github.com/Suinar/Bank-proto/repository/common"
	gomock "github.com/golang/mock/gomock"
)

// MockICardService is a mock of ICardService interface.
type MockICardService struct {
	ctrl     *gomock.Controller
	recorder *MockICardServiceMockRecorder
}

// MockICardServiceMockRecorder is the mock recorder for MockICardService.
type MockICardServiceMockRecorder struct {
	mock *MockICardService
}

// NewMockICardService creates a new mock instance.
func NewMockICardService(ctrl *gomock.Controller) *MockICardService {
	mock := &MockICardService{ctrl: ctrl}
	mock.recorder = &MockICardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICardService) EXPECT() *MockICardServiceMockRecorder {
	return m.recorder
}

// Blocking mocks base method.
func (m *MockICardService) Blocking(ctx context.Context, req *common.IdRequest) (*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocking", ctx, req)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocking indicates an expected call of Blocking.
func (mr *MockICardServiceMockRecorder) Blocking(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocking", reflect.TypeOf((*MockICardService)(nil).Blocking), ctx, req)
}

// Create mocks base method.
func (m *MockICardService) Create(ctx context.Context, req *card.Card) (*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICardServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICardService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockICardService) Delete(ctx context.Context, req *common.IdRequest) (*common.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockICardServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICardService)(nil).Delete), ctx, req)
}

// GetAll mocks base method.
func (m *MockICardService) GetAll(ctx context.Context, req *common.Empty) (*card.CardList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, req)
	ret0, _ := ret[0].(*card.CardList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICardServiceMockRecorder) GetAll(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICardService)(nil).GetAll), ctx, req)
}

// GetById mocks base method.
func (m *MockICardService) GetById(ctx context.Context, req *common.IdRequest) (*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, req)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICardServiceMockRecorder) GetById(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICardService)(nil).GetById), ctx, req)
}

// GetByNumber mocks base method.
func (m *MockICardService) GetByNumber(ctx context.Context, req *card.CardNumberRequest) (*card.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNumber", ctx, req)
	ret0, _ := ret[0].(*card.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNumber indicates an expected call of GetByNumber.
func (mr *MockICardServiceMockRecorder) GetByNumber(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNumber", reflect.TypeOf((*MockICardService)(nil).GetByNumber), ctx, req)
}

// GetByUser mocks base method.
func (m *MockICardService) GetByUser(ctx context.Context, req *common.UserIdRequest) (*card.CardList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, req)
	ret0, _ := ret[0].(*card.CardList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockICardServiceMockRecorder) GetByUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockICardService)(nil).GetByUser), ctx, req)
}
