// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/Suinar/Bank-proto/repository/common"
	credit "github.com/Suinar/Bank-proto/repository/credit"
	gomock "github.com/golang/mock/gomock"
)

// MockICreditService is a mock of ICreditService interface.
type MockICreditService struct {
	ctrl     *gomock.Controller
	recorder *MockICreditServiceMockRecorder
}

// MockICreditServiceMockRecorder is the mock recorder for MockICreditService.
type MockICreditServiceMockRecorder struct {
	mock *MockICreditService
}

// NewMockICreditService creates a new mock instance.
func NewMockICreditService(ctrl *gomock.Controller) *MockICreditService {
	mock := &MockICreditService{ctrl: ctrl}
	mock.recorder = &MockICreditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreditService) EXPECT() *MockICreditServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICreditService) Create(ctx context.Context, req *credit.Credit) (*credit.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*credit.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICreditServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICreditService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockICreditService) Delete(ctx context.Context, req *common.IdRequest) (*common.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockICreditServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICreditService)(nil).Delete), ctx, req)
}

// GetAll mocks base method.
func (m *MockICreditService) GetAll(ctx context.Context, req *common.Empty) (*credit.CreditList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, req)
	ret0, _ := ret[0].(*credit.CreditList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICreditServiceMockRecorder) GetAll(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICreditService)(nil).GetAll), ctx, req)
}

// GetById mocks base method.
func (m *MockICreditService) GetById(ctx context.Context, req *common.IdRequest) (*credit.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, req)
	ret0, _ := ret[0].(*credit.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICreditServiceMockRecorder) GetById(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICreditService)(nil).GetById), ctx, req)
}

// GetByUser mocks base method.
func (m *MockICreditService) GetByUser(ctx context.Context, req *common.UserIdRequest) (*credit.CreditList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, req)
	ret0, _ := ret[0].(*credit.CreditList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockICreditServiceMockRecorder) GetByUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockICreditService)(nil).GetByUser), ctx, req)
}

// Repay mocks base method.
func (m *MockICreditService) Repay(ctx context.Context, req *common.AmountRequest) (*credit.Credit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repay", ctx, req)
	ret0, _ := ret[0].(*credit.Credit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repay indicates an expected call of Repay.
func (mr *MockICreditServiceMockRecorder) Repay(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repay", reflect.TypeOf((*MockICreditService)(nil).Repay), ctx, req)
}
