// Code generated by MockGen. DO NOT EDIT.
// Source: interface_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/Suinar/Bank-proto/repository/common"
	currency "github.com/Suinar/Bank-proto/repository/currency"
)

// MockICurrencyService is a mock of ICurrencyService interface.
type MockICurrencyService struct {
	ctrl     *gomock.Controller
	recorder *MockICurrencyServiceMockRecorder
}

// MockICurrencyServiceMockRecorder is the mock recorder for MockICurrencyService.
type MockICurrencyServiceMockRecorder struct {
	mock *MockICurrencyService
}

// NewMockICurrencyService creates a new mock instance.
func NewMockICurrencyService(ctrl *gomock.Controller) *MockICurrencyService {
	mock := &MockICurrencyService{ctrl: ctrl}
	mock.recorder = &MockICurrencyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICurrencyService) EXPECT() *MockICurrencyServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICurrencyService) Create(ctx context.Context, req *currency.Currency) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICurrencyServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICurrencyService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockICurrencyService) Delete(ctx context.Context, req *common.IdRequest) (*common.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*common.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockICurrencyServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICurrencyService)(nil).Delete), ctx, req)
}

// GetAll mocks base method.
func (m *MockICurrencyService) GetAll(ctx context.Context, req *common.Empty) (*currency.CurrencyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, req)
	ret0, _ := ret[0].(*currency.CurrencyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockICurrencyServiceMockRecorder) GetAll(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockICurrencyService)(nil).GetAll), ctx, req)
}

// GetById mocks base method.
func (m *MockICurrencyService) GetById(ctx context.Context, req *common.IdRequest) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, req)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockICurrencyServiceMockRecorder) GetById(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockICurrencyService)(nil).GetById), ctx, req)
}

// GetByIso mocks base method.
func (m *MockICurrencyService) GetByIso(ctx context.Context, req *currency.IsoCodeRequest) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIso", ctx, req)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIso indicates an expected call of GetByIso.
func (mr *MockICurrencyServiceMockRecorder) GetByIso(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIso", reflect.TypeOf((*MockICurrencyService)(nil).GetByIso), ctx, req)
}

// GetBySymbol mocks base method.
func (m *MockICurrencyService) GetBySymbol(ctx context.Context, req *currency.SymbolRequest) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySymbol", ctx, req)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySymbol indicates an expected call of GetBySymbol.
func (mr *MockICurrencyServiceMockRecorder) GetBySymbol(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySymbol", reflect.TypeOf((*MockICurrencyService)(nil).GetBySymbol), ctx, req)
}

// Update mocks base method.
func (m *MockICurrencyService) Update(ctx context.Context, req *currency.UpdateCurrencyRequest) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockICurrencyServiceMockRecorder) Update(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICurrencyService)(nil).Update), ctx, req)
}
