// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: repository/card/card.proto

package __

import (
	common "Bank-repository-service/proto/repository/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardStatus int32

const (
	CardStatus_CARD_STATUS_CLOSED  CardStatus = 0
	CardStatus_CARD_STATUS_ACTIVE  CardStatus = 1
	CardStatus_CARD_STATUS_BLOCKED CardStatus = 2
	CardStatus_CARD_STATUS_EXPIRED CardStatus = 3
)

// Enum value maps for CardStatus.
var (
	CardStatus_name = map[int32]string{
		0: "CARD_STATUS_CLOSED",
		1: "CARD_STATUS_ACTIVE",
		2: "CARD_STATUS_BLOCKED",
		3: "CARD_STATUS_EXPIRED",
	}
	CardStatus_value = map[string]int32{
		"CARD_STATUS_CLOSED":  0,
		"CARD_STATUS_ACTIVE":  1,
		"CARD_STATUS_BLOCKED": 2,
		"CARD_STATUS_EXPIRED": 3,
	}
)

func (x CardStatus) Enum() *CardStatus {
	p := new(CardStatus)
	*p = x
	return p
}

func (x CardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_card_card_proto_enumTypes[0].Descriptor()
}

func (CardStatus) Type() protoreflect.EnumType {
	return &file_repository_card_card_proto_enumTypes[0]
}

func (x CardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardStatus.Descriptor instead.
func (CardStatus) EnumDescriptor() ([]byte, []int) {
	return file_repository_card_card_proto_rawDescGZIP(), []int{0}
}

type CardNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardNumberRequest) Reset() {
	*x = CardNumberRequest{}
	mi := &file_repository_card_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardNumberRequest) ProtoMessage() {}

func (x *CardNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_card_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardNumberRequest.ProtoReflect.Descriptor instead.
func (*CardNumberRequest) Descriptor() ([]byte, []int) {
	return file_repository_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *CardNumberRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Number        string                 `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	ExpiryMonth   int32                  `protobuf:"varint,5,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    int32                  `protobuf:"varint,6,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	Status        CardStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=repository.card.CardStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_repository_card_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_repository_card_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_repository_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Card) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Card) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetExpiryMonth() int32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *Card) GetExpiryYear() int32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

func (x *Card) GetStatus() CardStatus {
	if x != nil {
		return x.Status
	}
	return CardStatus_CARD_STATUS_CLOSED
}

type CardCreateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardCreateInput) Reset() {
	*x = CardCreateInput{}
	mi := &file_repository_card_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardCreateInput) ProtoMessage() {}

func (x *CardCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_repository_card_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardCreateInput.ProtoReflect.Descriptor instead.
func (*CardCreateInput) Descriptor() ([]byte, []int) {
	return file_repository_card_card_proto_rawDescGZIP(), []int{2}
}

func (x *CardCreateInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CardCreateInput) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type CardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardList) Reset() {
	*x = CardList{}
	mi := &file_repository_card_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardList) ProtoMessage() {}

func (x *CardList) ProtoReflect() protoreflect.Message {
	mi := &file_repository_card_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardList.ProtoReflect.Descriptor instead.
func (*CardList) Descriptor() ([]byte, []int) {
	return file_repository_card_card_proto_rawDescGZIP(), []int{3}
}

func (x *CardList) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_repository_card_card_proto protoreflect.FileDescriptor

const file_repository_card_card_proto_rawDesc = "" +
	"\n" +
	"\x1arepository/card/card.proto\x12\x0frepository.card\x1a\x17repository/common.proto\"+\n" +
	"\x11CardNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\"\xdf\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06number\x18\x04 \x01(\tR\x06number\x12!\n" +
	"\fexpiry_month\x18\x05 \x01(\x05R\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x06 \x01(\x05R\n" +
	"expiryYear\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.repository.card.CardStatusR\x06status\"I\n" +
	"\x0fCardCreateInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"7\n" +
	"\bCardList\x12+\n" +
	"\x05cards\x18\x01 \x03(\v2\x15.repository.card.CardR\x05cards*n\n" +
	"\n" +
	"CardStatus\x12\x16\n" +
	"\x12CARD_STATUS_CLOSED\x10\x00\x12\x16\n" +
	"\x12CARD_STATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13CARD_STATUS_BLOCKED\x10\x02\x12\x17\n" +
	"\x13CARD_STATUS_EXPIRED\x10\x032\xf2\x03\n" +
	"\x0eCardRepository\x12=\n" +
	"\x06GetAll\x12\x18.repository.common.Empty\x1a\x19.repository.card.CardList\x12H\n" +
	"\tGetByUser\x12 .repository.common.UserIdRequest\x1a\x19.repository.card.CardList\x12>\n" +
	"\aGetById\x12\x1c.repository.common.IdRequest\x1a\x15.repository.card.Card\x12H\n" +
	"\vGetByNumber\x12\".repository.card.CardNumberRequest\x1a\x15.repository.card.Card\x12?\n" +
	"\bBlocking\x12\x1c.repository.common.IdRequest\x1a\x15.repository.card.Card\x12A\n" +
	"\x06Create\x12 .repository.card.CardCreateInput\x1a\x15.repository.card.Card\x12I\n" +
	"\x06Delete\x12\x1c.repository.common.IdRequest\x1a!.repository.common.DeleteResponseB\x03Z\x01/b\x06proto3"

var (
	file_repository_card_card_proto_rawDescOnce sync.Once
	file_repository_card_card_proto_rawDescData []byte
)

func file_repository_card_card_proto_rawDescGZIP() []byte {
	file_repository_card_card_proto_rawDescOnce.Do(func() {
		file_repository_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_card_card_proto_rawDesc), len(file_repository_card_card_proto_rawDesc)))
	})
	return file_repository_card_card_proto_rawDescData
}

var file_repository_card_card_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repository_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_repository_card_card_proto_goTypes = []any{
	(CardStatus)(0),               // 0: repository.card.CardStatus
	(*CardNumberRequest)(nil),     // 1: repository.card.CardNumberRequest
	(*Card)(nil),                  // 2: repository.card.Card
	(*CardCreateInput)(nil),       // 3: repository.card.CardCreateInput
	(*CardList)(nil),              // 4: repository.card.CardList
	(*common.Empty)(nil),          // 5: repository.common.Empty
	(*common.UserIdRequest)(nil),  // 6: repository.common.UserIdRequest
	(*common.IdRequest)(nil),      // 7: repository.common.IdRequest
	(*common.DeleteResponse)(nil), // 8: repository.common.DeleteResponse
}
var file_repository_card_card_proto_depIdxs = []int32{
	0, // 0: repository.card.Card.status:type_name -> repository.card.CardStatus
	2, // 1: repository.card.CardList.cards:type_name -> repository.card.Card
	5, // 2: repository.card.CardRepository.GetAll:input_type -> repository.common.Empty
	6, // 3: repository.card.CardRepository.GetByUser:input_type -> repository.common.UserIdRequest
	7, // 4: repository.card.CardRepository.GetById:input_type -> repository.common.IdRequest
	1, // 5: repository.card.CardRepository.GetByNumber:input_type -> repository.card.CardNumberRequest
	7, // 6: repository.card.CardRepository.Blocking:input_type -> repository.common.IdRequest
	3, // 7: repository.card.CardRepository.Create:input_type -> repository.card.CardCreateInput
	7, // 8: repository.card.CardRepository.Delete:input_type -> repository.common.IdRequest
	4, // 9: repository.card.CardRepository.GetAll:output_type -> repository.card.CardList
	4, // 10: repository.card.CardRepository.GetByUser:output_type -> repository.card.CardList
	2, // 11: repository.card.CardRepository.GetById:output_type -> repository.card.Card
	2, // 12: repository.card.CardRepository.GetByNumber:output_type -> repository.card.Card
	2, // 13: repository.card.CardRepository.Blocking:output_type -> repository.card.Card
	2, // 14: repository.card.CardRepository.Create:output_type -> repository.card.Card
	8, // 15: repository.card.CardRepository.Delete:output_type -> repository.common.DeleteResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_repository_card_card_proto_init() }
func file_repository_card_card_proto_init() {
	if File_repository_card_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_card_card_proto_rawDesc), len(file_repository_card_card_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_card_card_proto_goTypes,
		DependencyIndexes: file_repository_card_card_proto_depIdxs,
		EnumInfos:         file_repository_card_card_proto_enumTypes,
		MessageInfos:      file_repository_card_card_proto_msgTypes,
	}.Build()
	File_repository_card_card_proto = out.File
	file_repository_card_card_proto_goTypes = nil
	file_repository_card_card_proto_depIdxs = nil
}
