// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: repository/card/card.proto

package card

import (
	context "context"
	common "Bank-repository-service/proto/repository/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardRepository_GetAll_FullMethodName      = "/repository.card.CardRepository/GetAll"
	CardRepository_GetByUser_FullMethodName   = "/repository.card.CardRepository/GetByUser"
	CardRepository_GetById_FullMethodName     = "/repository.card.CardRepository/GetById"
	CardRepository_GetByNumber_FullMethodName = "/repository.card.CardRepository/GetByNumber"
	CardRepository_Blocking_FullMethodName    = "/repository.card.CardRepository/Blocking"
	CardRepository_Create_FullMethodName      = "/repository.card.CardRepository/Create"
	CardRepository_Delete_FullMethodName      = "/repository.card.CardRepository/Delete"
)

// CardRepositoryClient is the client API for CardRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardRepositoryClient interface {
	GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CardList, error)
	GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*CardList, error)
	GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Card, error)
	GetByNumber(ctx context.Context, in *CardNumberRequest, opts ...grpc.CallOption) (*Card, error)
	Blocking(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Card, error)
	Create(ctx context.Context, in *Card, opts ...grpc.CallOption) (*Card, error)
	Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error)
}

type cardRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewCardRepositoryClient(cc grpc.ClientConnInterface) CardRepositoryClient {
	return &cardRepositoryClient{cc}
}

func (c *cardRepositoryClient) GetAll(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CardList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardList)
	err := c.cc.Invoke(ctx, CardRepository_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRepositoryClient) GetByUser(ctx context.Context, in *common.UserIdRequest, opts ...grpc.CallOption) (*CardList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardList)
	err := c.cc.Invoke(ctx, CardRepository_GetByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRepositoryClient) GetById(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Card, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Card)
	err := c.cc.Invoke(ctx, CardRepository_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRepositoryClient) GetByNumber(ctx context.Context, in *CardNumberRequest, opts ...grpc.CallOption) (*Card, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Card)
	err := c.cc.Invoke(ctx, CardRepository_GetByNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRepositoryClient) Blocking(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*Card, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Card)
	err := c.cc.Invoke(ctx, CardRepository_Blocking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRepositoryClient) Create(ctx context.Context, in *Card, opts ...grpc.CallOption) (*Card, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Card)
	err := c.cc.Invoke(ctx, CardRepository_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardRepositoryClient) Delete(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.DeleteResponse)
	err := c.cc.Invoke(ctx, CardRepository_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardRepositoryServer is the server API for CardRepository service.
// All implementations must embed UnimplementedCardRepositoryServer
// for forward compatibility.
type CardRepositoryServer interface {
	GetAll(context.Context, *common.Empty) (*CardList, error)
	GetByUser(context.Context, *common.UserIdRequest) (*CardList, error)
	GetById(context.Context, *common.IdRequest) (*Card, error)
	GetByNumber(context.Context, *CardNumberRequest) (*Card, error)
	Blocking(context.Context, *common.IdRequest) (*Card, error)
	Create(context.Context, *Card) (*Card, error)
	Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error)
	mustEmbedUnimplementedCardRepositoryServer()
}

// UnimplementedCardRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardRepositoryServer struct{}

func (UnimplementedCardRepositoryServer) GetAll(context.Context, *common.Empty) (*CardList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCardRepositoryServer) GetByUser(context.Context, *common.UserIdRequest) (*CardList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByUser not implemented")
}
func (UnimplementedCardRepositoryServer) GetById(context.Context, *common.IdRequest) (*Card, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedCardRepositoryServer) GetByNumber(context.Context, *CardNumberRequest) (*Card, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByNumber not implemented")
}
func (UnimplementedCardRepositoryServer) Blocking(context.Context, *common.IdRequest) (*Card, error) {
	return nil, status.Error(codes.Unimplemented, "method Blocking not implemented")
}
func (UnimplementedCardRepositoryServer) Create(context.Context, *Card) (*Card, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCardRepositoryServer) Delete(context.Context, *common.IdRequest) (*common.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCardRepositoryServer) mustEmbedUnimplementedCardRepositoryServer() {}
func (UnimplementedCardRepositoryServer) testEmbeddedByValue()                        {}

// UnsafeCardRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardRepositoryServer will
// result in compilation errors.
type UnsafeCardRepositoryServer interface {
	mustEmbedUnimplementedCardRepositoryServer()
}

func RegisterCardRepositoryServer(s grpc.ServiceRegistrar, srv CardRepositoryServer) {
	// If the following call panics, it indicates UnimplementedCardRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardRepository_ServiceDesc, srv)
}

func _CardRepository_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRepositoryServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRepository_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRepositoryServer).GetAll(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRepository_GetByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRepositoryServer).GetByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRepository_GetByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRepositoryServer).GetByUser(ctx, req.(*common.UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRepository_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRepositoryServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRepository_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRepositoryServer).GetById(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRepository_GetByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRepositoryServer).GetByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRepository_GetByNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRepositoryServer).GetByNumber(ctx, req.(*CardNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRepository_Blocking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRepositoryServer).Blocking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRepository_Blocking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRepositoryServer).Blocking(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Card)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRepository_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRepositoryServer).Create(ctx, req.(*Card))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardRepository_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardRepositoryServer).Delete(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardRepository_ServiceDesc is the grpc.ServiceDesc for CardRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.card.CardRepository",
	HandlerType: (*CardRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _CardRepository_GetAll_Handler,
		},
		{
			MethodName: "GetByUser",
			Handler:    _CardRepository_GetByUser_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _CardRepository_GetById_Handler,
		},
		{
			MethodName: "GetByNumber",
			Handler:    _CardRepository_GetByNumber_Handler,
		},
		{
			MethodName: "Blocking",
			Handler:    _CardRepository_Blocking_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CardRepository_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CardRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/card/card.proto",
}
